[env:esp32dev]
platform = espressif32 @ 7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -DCORE_DEBUG_LEVEL=3 -Wl,--wrap=esp_bt_gap_register_callback -Wl,--wrap=uartWrite -Wl,--wrap=uartWriteBuf -Wl,--wrap=_write_r -Wl,--wrap=esp_vfs_write
