"""Constants for Denon App Volume."""

DOMAIN = "denon_app_volume"

API_VERSION = 1
BACKUP_SCHEMA = 1
BACKUP_SAVE_DELAY_SECONDS = 10
DEFAULT_PORT = 80
HEARTBEAT_SECONDS = 5
MAX_APPS = 16
MAX_APP_ID_LENGTH = 96
MAX_APP_NAME_LENGTH = 64
MAX_VOLUME_RAW = 196
REQUEST_TIMEOUT_SECONDS = 5

ATTR_APP_ID = "app_id"
ATTR_APP_NAME = "app_name"
